### ISSUE TITLE
App Installer failed to install package dependencies

### ISSUE THREAD

**Issue by richo67** [Angelelz/Pass4Kee#1]
Hello,
I wanted to try your program but when I run the bundle after downloading the my win10 returned following error:
App Installer failed to install package dependencies. Ask the developer for Microsoft.VCLibs.140.00.Debug package.

**Comment by richo67** [comment]
It would be perhaps, better to build non-debug version?

**Comment by Angelelz** [comment]
Yeah, I dont know how to do that. I'll come back

**Comment by Angelelz** [comment]
You can try that again now. Let me know please

**Comment by lachtan86** [comment]
Hello, i want to try your app too. Ver 0.9.8.0 failed to install: 
Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

**Comment by Angelelz** [comment]
This is what I found: https://stackoverflow.com/questions/23812471/installing-appx-without-trusted-certificate/24372483
I should probably publish it on the store for easy access but I'd need to make an icon and stuff I've never done, I'not a developer and I've never done any of this before, perhaps someone could help me out.

**Comment by lachtan86** [comment]
Thats right, it works after installation certificate to Trusted People store.

edit: Now I completed install it with AutoHotkey and fully working. Its great!

Thank You for your work ;)
