### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by ajjon** [Angelelz/Pass4Kee#2]
Tried to install Pass4Kee, but the validation time for the certificate have passed.
Certificate date is only valid until 2018-12-02.

**Comment by S34NN** [comment]
Same issue here as I just came across your project while searching. It's a clever idea and I appreciate you sharing your work. I hope you are able to renew the certificate. I wish I could contribute but I don't have any programming skill.

Edit: So I decided to figure out how to re-create the app package myself using Visual Studio, despite knowing very little about programming (other than some basic AHK scripting). App installed fine with a new cert and is working great paired with a AHK script. Also made some tweaks to the design (Dark Theme) and fixed a typo on the button. Thanks again @Angelelz for sharing.

**Comment by ajjon** [comment]
@S34NN Same here, working superb when compiling yourself. Certificate updates. Closing issue.
